// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Audit struct {
	ID           string  `json:"id"`
	Identifier   string  `json:"identifier"`
	UserEmail    *string `json:"user_email,omitempty"`
	UserName     *string `json:"user_name,omitempty"`
	Method       string  `json:"method"`
	Path         string  `json:"path"`
	StatusCode   *int32  `json:"status_code,omitempty"`
	ServiceName  string  `json:"service_name"`
	Timestamp    string  `json:"timestamp"`
	ResponseTime *int32  `json:"response_time,omitempty"`
}

type AuditList struct {
	Data       []*AuditSummary `json:"data"`
	Pagination *Pagination     `json:"pagination"`
}

type AuditSummary struct {
	ID           string  `json:"id"`
	Identifier   string  `json:"identifier"`
	UserEmail    *string `json:"user_email,omitempty"`
	UserName     *string `json:"user_name,omitempty"`
	Method       string  `json:"method"`
	Path         string  `json:"path"`
	StatusCode   *int32  `json:"status_code,omitempty"`
	ServiceName  string  `json:"service_name"`
	Timestamp    string  `json:"timestamp"`
	ResponseTime *int32  `json:"response_time,omitempty"`
}

type Pagination struct {
	Limit      int32 `json:"limit"`
	Page       int32 `json:"page"`
	TotalItems int32 `json:"totalItems"`
	TotalPage  int32 `json:"totalPage"`
}

type Query struct {
}
