/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutIndexRouteImport } from './routes/app/_layout/index'
import { Route as AppLayoutSessionsRouteImport } from './routes/app/_layout/sessions'
import { Route as AppLayoutMembersRouteImport } from './routes/app/_layout/members'
import { Route as AppLayoutAnomaliesRouteImport } from './routes/app/_layout/anomalies'
import { Route as AppLayoutSettingsRetentionRouteImport } from './routes/app/_layout/settings/retention'
import { Route as AppLayoutSettingsNotificationsRouteImport } from './routes/app/_layout/settings/notifications'
import { Route as AppLayoutSettingsApiKeysRouteImport } from './routes/app/_layout/settings/api-keys'

const AppRouteImport = createFileRoute('/app')()

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppRoute,
} as any)
const AppLayoutIndexRoute = AppLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSessionsRoute = AppLayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutMembersRoute = AppLayoutMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutAnomaliesRoute = AppLayoutAnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSettingsRetentionRoute =
  AppLayoutSettingsRetentionRouteImport.update({
    id: '/settings/retention',
    path: '/settings/retention',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutSettingsNotificationsRoute =
  AppLayoutSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppLayoutRoute,
  } as any)
const AppLayoutSettingsApiKeysRoute =
  AppLayoutSettingsApiKeysRouteImport.update({
    id: '/settings/api-keys',
    path: '/settings/api-keys',
    getParentRoute: () => AppLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/anomalies': typeof AppLayoutAnomaliesRoute
  '/app/members': typeof AppLayoutMembersRoute
  '/app/sessions': typeof AppLayoutSessionsRoute
  '/app/': typeof AppLayoutIndexRoute
  '/app/settings/api-keys': typeof AppLayoutSettingsApiKeysRoute
  '/app/settings/notifications': typeof AppLayoutSettingsNotificationsRoute
  '/app/settings/retention': typeof AppLayoutSettingsRetentionRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/app': typeof AppLayoutIndexRoute
  '/app/anomalies': typeof AppLayoutAnomaliesRoute
  '/app/members': typeof AppLayoutMembersRoute
  '/app/sessions': typeof AppLayoutSessionsRoute
  '/app/settings/api-keys': typeof AppLayoutSettingsApiKeysRoute
  '/app/settings/notifications': typeof AppLayoutSettingsNotificationsRoute
  '/app/settings/retention': typeof AppLayoutSettingsRetentionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/app': typeof AppRouteWithChildren
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/anomalies': typeof AppLayoutAnomaliesRoute
  '/app/_layout/members': typeof AppLayoutMembersRoute
  '/app/_layout/sessions': typeof AppLayoutSessionsRoute
  '/app/_layout/': typeof AppLayoutIndexRoute
  '/app/_layout/settings/api-keys': typeof AppLayoutSettingsApiKeysRoute
  '/app/_layout/settings/notifications': typeof AppLayoutSettingsNotificationsRoute
  '/app/_layout/settings/retention': typeof AppLayoutSettingsRetentionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/app'
    | '/app/anomalies'
    | '/app/members'
    | '/app/sessions'
    | '/app/'
    | '/app/settings/api-keys'
    | '/app/settings/notifications'
    | '/app/settings/retention'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/app'
    | '/app/anomalies'
    | '/app/members'
    | '/app/sessions'
    | '/app/settings/api-keys'
    | '/app/settings/notifications'
    | '/app/settings/retention'
  id:
    | '__root__'
    | '/login'
    | '/app'
    | '/app/_layout'
    | '/app/_layout/anomalies'
    | '/app/_layout/members'
    | '/app/_layout/sessions'
    | '/app/_layout/'
    | '/app/_layout/settings/api-keys'
    | '/app/_layout/settings/notifications'
    | '/app/_layout/settings/retention'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_layout/': {
      id: '/app/_layout/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppLayoutIndexRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/sessions': {
      id: '/app/_layout/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppLayoutSessionsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/members': {
      id: '/app/_layout/members'
      path: '/members'
      fullPath: '/app/members'
      preLoaderRoute: typeof AppLayoutMembersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/anomalies': {
      id: '/app/_layout/anomalies'
      path: '/anomalies'
      fullPath: '/app/anomalies'
      preLoaderRoute: typeof AppLayoutAnomaliesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/retention': {
      id: '/app/_layout/settings/retention'
      path: '/settings/retention'
      fullPath: '/app/settings/retention'
      preLoaderRoute: typeof AppLayoutSettingsRetentionRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/notifications': {
      id: '/app/_layout/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppLayoutSettingsNotificationsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/settings/api-keys': {
      id: '/app/_layout/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/app/settings/api-keys'
      preLoaderRoute: typeof AppLayoutSettingsApiKeysRouteImport
      parentRoute: typeof AppLayoutRoute
    }
  }
}

interface AppLayoutRouteChildren {
  AppLayoutAnomaliesRoute: typeof AppLayoutAnomaliesRoute
  AppLayoutMembersRoute: typeof AppLayoutMembersRoute
  AppLayoutSessionsRoute: typeof AppLayoutSessionsRoute
  AppLayoutIndexRoute: typeof AppLayoutIndexRoute
  AppLayoutSettingsApiKeysRoute: typeof AppLayoutSettingsApiKeysRoute
  AppLayoutSettingsNotificationsRoute: typeof AppLayoutSettingsNotificationsRoute
  AppLayoutSettingsRetentionRoute: typeof AppLayoutSettingsRetentionRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutAnomaliesRoute: AppLayoutAnomaliesRoute,
  AppLayoutMembersRoute: AppLayoutMembersRoute,
  AppLayoutSessionsRoute: AppLayoutSessionsRoute,
  AppLayoutIndexRoute: AppLayoutIndexRoute,
  AppLayoutSettingsApiKeysRoute: AppLayoutSettingsApiKeysRoute,
  AppLayoutSettingsNotificationsRoute: AppLayoutSettingsNotificationsRoute,
  AppLayoutSettingsRetentionRoute: AppLayoutSettingsRetentionRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

interface AppRouteChildren {
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppLayoutRoute: AppLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
